apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-data-pvc       # Name of your PVC
  namespace: kubeflow-user-example-com  # CHANGE THIS to your namespace
spec:
  accessModes:
    - ReadWriteOnce             # RWO: Mounted by 1 node (Standard Block Storage)
    # - ReadWriteMany           # RWX: Mounted by many nodes (NFS/EFS/Filestore)
  resources:
    requests:
      storage: 50Gi             # Size of the volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-workspace-pvc       # Name of your PVC
  namespace: kubeflow-user-example-com  # CHANGE THIS to your namespace
spec:
  accessModes:
    - ReadWriteOnce             # RWO: Mounted by 1 node (Standard Block Storage)
    # - ReadWriteMany           # RWX: Mounted by many nodes (NFS/EFS/Filestore)
  resources:
    requests:
      storage: 50Gi             # Size of the volume
