apiVersion: v1
kind: Pod
metadata:
  name: rescue-pod
  namespace: kubeflow-user-example-com
spec:
  containers:
  - name: rescue-container
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /mnt/models          # Where you want to see the files inside the pod
      name: rescue-storage      # Must match the name in 'volumes' below
  volumes:
  - name: rescue-storage        # Arbitrary name for this link
    persistentVolumeClaim:
      claimName: llm-workspace-pvc
  restartPolicy: Always